version: "3.3"
services:
  database:
    image: postgres:14.6-alpine
    container_name: db_app
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    container_name: redis_app
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./management:/management
    command: ["/user_manage/entrypoint.sh"]
    depends_on:
      - database
      - redis

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - database
