name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - actions
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Testing
        run: |
          docker-compose -f docker-compose.yml exec --tty app pytest

      - name: Linting
        run: |
          docker-compose -f docker-compose.yml exec --tty app black /management

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: dumitru8/user_manage:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop user_manage || true
            docker rm user_manage || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/user_manage:latest
            docker run -d -p 80:80 --name user_manage ${{ secrets.DOCKER_USERNAME }}/user_manage:latest
